/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Proyecto_1;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public void prue() {
    	int risas=1+1;
    }
}
